[build]
  # Directory to publish (current directory)
  publish = "."
  
  # Build command (not needed for static site)
  command = ""

[build.environment]
  # Node.js version (if needed)
  NODE_VERSION = "18"

[[headers]]
  # Apply these headers to all routes
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Don't cache HTML files
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  # Handle SPA routing (if needed in future)
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Form handling (if you want to use Netlify Forms instead of mailto)
# Uncomment the following lines if you want to use Netlify's form handling
# [build]
#   functions = "netlify/functions"

# Enable Netlify Forms
[build.environment]
  NETLIFY_FORMS = "true"
